-- MilesHighClub schema (Supabase)
-- Primary datastore: Supabase Postgres, project mesqxoujuxothdqjwhwd.
-- Tables: users_list, bookings (managed in the Supabase dashboard).
--
-- users_list: { telegram_id (pk), role, phone, address, unit, credits, created_at }
-- bookings:   { id (uuid pk), customer_id -> users_list.telegram_id, start_time, end_time,
--               pax, location, transport_option, quote_price, status, created_at }
--
-- Access from the Mini App uses the anon key, so RLS must allow it.
-- Run these in the Supabase SQL Editor if RLS is blocking reads/writes:

-- If RLS is enabled on these tables, the anon role needs open policies for now
-- (auth is Telegram-identity based in the app, not Supabase auth):
-- alter table public.users_list enable row level security;
-- alter table public.bookings   enable row level security;
-- create policy "anon full access users" on public.users_list for all to anon using (true) with check (true);
-- create policy "anon full access bookings" on public.bookings for all to anon using (true) with check (true);
